#!/bin/sh
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/dmenu_run
        hist=$cachedir/dmenu_hist
else
	cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
        hist=$HOME/.dmenu_hist
fi
(
	IFS=:
	if stest -dqr -n "$cache" $PATH; then
		stest -flx $PATH | sort -u | tee "$cache" | dmenu -hist $hist "$@"
	else
		dmenu -hist $hist "$@" < "$cache"
	fi
) | ${SHELL:-"/bin/sh"} &
